### ISSUE TITLE
detail fait crash lorsqu'on s'amuse avec

### ISSUE THREAD

**Issue by remipichon** [24HeuresINSA/24h-android-app#126]
Process: com.insalyon.les24heures, PID: 10570
    java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 2, found: 0 Pager id: com.insalyon.les24heures:id/jazzy_pager Pager class: class com.insalyon.les24heures.JazzyViewPager.JazzyViewPager Problematic adapter: class com.insalyon.les24heures.fragments.DetailFragment$MainAdapter
            at android.support.v4.view.ViewPager.populate(ViewPager.java:967)

**Comment by remipichon** [comment]
Impossible a reproduire....

**Comment by LucasBettarel** [comment]
c'est ça ?
je cliquait sur un item de la liste day puis revenait sur la liste rapidement, puis clique un autre item

05-04 22:57:26.759  24314-24314/com.insalyon.les24heures E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.insalyon.les24heures, PID: 24314
    java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 1, found: 2 Pager id: com.insalyon.les24heures:id/jazzy_pager Pager class: class com.insalyon.les24heures.JazzyViewPager.JazzyViewPager Problematic adapter: class com.insalyon.les24heures.fragments.DetailFragment$MainAdapter
            at android.support.v4.view.ViewPager.populate(ViewPager.java:967)
            at android.support.v4.view.ViewPager.populate(ViewPager.java:919)
            at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1441)
            at android.view.View.measure(View.java:17547)
            at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:727)
            at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:463)
            at android.view.View.measure(View.java:17547)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
            at android.view.View.measure(View.java:17547)
            at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1260)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
            at android.widget.ScrollView.onMeasure(ScrollView.java:337)
            at android.view.View.measure(View.java:17547)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
            at android.view.View.measure(View.java:17547)
            at com.sothree.slidinguppanel.SlidingUpPanelLayout.onMeasure(SlidingUpPanelLayout.java:734)
            at com.insalyon.les24heures.view.DetailSlidingUpPanelLayout.onMeasure(DetailSlidingUpPanelLayout.java:303)
            at android.view.View.measure(View.java:17547)
            at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:851)
            at android.view.View.measure(View.java:17547)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
            at android.view.View.measure(View.java:17547)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
            at android.view.View.measure(View.java:17547)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
            at com.android.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:447)
            at android.view.View.measure(View.java:17547)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2615)
            at android.view.View.measure(View.java:17547)
            at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2015)
            at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1173)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1379)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
            at android.view.Choreographer.doCallbacks(Choreographer.java:580)
            at android.view.Choreographer.doFrame(Choreographer.java:550)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.Zygot

**Comment by remipichon** [comment]
Je regarde si c'est ca

**Comment by remipichon** [comment]
avec quoi retournais tu ? back touch ? back appname ? touch on header ?

**Comment by LucasBettarel** [comment]
back touch oui



Lucas Bettarel

2015-05-04 23:32 GMT+08:00 Remi Pichon <notifications@github.com>:

**Comment by remipichon** [comment]
As tu réussi à le reproduire plusieurs fois ? Si tu y arrives de nouveau, pourras tu filmer ce que tu fais ?

**Comment by LucasBettarel** [comment]
oui 2 fois d'affile actually
Ok je retente ce soir



Lucas Bettarel
