### ISSUE TITLE
Crash when rotating screen

### ISSUE THREAD

**Issue by lbillon** [24HeuresINSA/24h-android-app#135]
Steps to reproduce : 
1. Start application
2. Rotate screen

App crashes with following error : 
```
04-27 17:40:27.483  10483-10483/com.insalyon.les24heures E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.insalyon.les24heures, PID: 10483
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.insalyon.les24heures/com.insalyon.les24heures.DayActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Boolean com.insalyon.les24heures.view.CustomDrawerLayout.isDrawerVisible()' on a null object reference
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3947)
            at android.app.ActivityThread.access$900(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Boolean com.insalyon.les24heures.view.CustomDrawerLayout.isDrawerVisible()' on a null object reference
            at com.insalyon.les24heures.BaseDynamicDataActivity.customOnOptionsMenu(BaseDynamicDataActivity.java:266)
            at com.insalyon.les24heures.BaseDynamicDataActivity.onPrepareOptionsMenu(BaseDynamicDataActivity.java:289)
            at android.app.Activity.onPreparePanel(Activity.java:2841)
            at com.android.internal.policy.impl.PhoneWindow.preparePanel(PhoneWindow.java:577)
            at com.android.internal.policy.impl.PhoneWindow.doInvalidatePanelMenu(PhoneWindow.java:921)
            at com.android.internal.policy.impl.PhoneWindow$1.run(PhoneWindow.java:259)
            at com.android.internal.policy.impl.PhoneWindow.doPendingInvalidatePanelMenu(PhoneWindow.java:892)
            at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2035)
            at android.app.Activity.onRestoreInstanceState(Activity.java:1023)
            at android.app.Activity.performRestoreInstanceState(Activity.java:978)
            at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1162)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3947)
            at android.app.ActivityThread.access$900(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by remipichon** [comment]
Est ce que tu le constates encore ? J'ai mis a jour la lib du detail sliding up pannem

**Comment by lbillon** [comment]
Dans quelle branche as-tu mis ça a jour ?

**Comment by remipichon** [comment]
Je sais plus quelle branche mais ca a deja été mergé, c'est sur "develop"

**Comment by remipichon** [comment]
sur lolipoop uniquement
